const DATA = [
  {
    id: "unfaced-hard",
    title: "Unfaced Brussels",
    by: "Unfaced",
    date: "2026-06-12",
    timeStart: "23:00",
    timeEnd: "05:45",
    venue: "Mirano",
    city: "Bruxelles",
    address: "Chaussée de Louvain 38, 1210 Saint-Josse-ten-Noode",
    price: 20.99,
    styles: ["Hard Techno", "Hardgroove"],
    ticketUrl: "https://shotgun.live/fr/events/unfaced-brussels-hard",
    lineup: ["Bøery", "Bp-Em", "Kaai", "Ondulada", "Xrtn"],
    image: "images/Unface-hard.avif",
  },

  {
    id: "playlabel-day",
    title: "Play Label — Congrès",
    by: "Play Label",
    date: "2026-06-13",
    timeStart: "14:00",
    timeEnd: "22:00",
    venue: "Colonne du Congrès",
    city: "Bruxelles",
    address: "Koningsstraat 77 · Place du Congrès, 1000 Bruxelles",
    price: 23.0,
    styles: ["House", "Disco"],
    ticketUrl: "https://tinyurl.com/OpenAir-Congres",
    lineup: [
      "The Blessed Madonna",
      "Jennifer Loveless",
      "Melissa Juice",
      "ttyfal",
    ],
    image: "images/playlabel-day.jpg",
  },

  {
    id: "unfaced-openair",
    title: "Unfaced Open Air",
    by: "Unfaced",
    date: "2026-06-13",
    timeStart: "14:00",
    timeEnd: "22:00",
    venue: "Place Jean Rey",
    city: "Bruxelles",
    address: "Place Jean Rey, 1040 Bruxelles",
    price: 27.99,
    styles: ["Techno", "Open Air"],
    ticketUrl: "https://shotgun.live/fr/events/unfaced-brussels-open-air",
    lineup: [
      "Jacidorex b2b Part Time Killer",
      "Jacidorex b2b Zwilling",
      "Riana Holley b2b Lola Cerise",
      "Hurts b2b Vespera",
    ],
    image: "images/Unfaced-dance.avif",
  },

  {
    id: "playlabel-after",
    title: "Play Label — Afterparty",
    by: "Play Label",
    date: "2026-06-13",
    timeStart: "22:00",
    timeEnd: "05:00",
    venue: "Secret Location",
    city: "Bruxelles",
    address: "Rue de Ligne 8, 1000 Bruxelles",
    price: 17.0,
    styles: ["Techno", "House"],
    lineup: [],
    ticketUrl: "https://tinyurl.com/AfterpartyxCongresOpenAir",
    text: "Afterparty à 200m du Congrès · capacité limitée · 21+ · LGBTQIA+ friendly · no phone policy.",
    image: "images/playlabel-after.jpg",
  },

  {
    id: "la-nature",
    title: "La Nature 2026 · Art & Music",
    by: "NoName",
    date: "2026-06-18",
    endDate: "2026-06-21",
    timeStart: "16:00",
    timeEnd: null,
    venue: "Baraque de Fraiture",
    city: "Vielsalm",
    address: "Baraque de Fraiture 6, 6690 Vielsalm",
    price: 200.0,
    styles: ["Techno", "Open Air"],
    lineup: [],
    ticketUrl:
      "https://www.ticketswap.com/festival-tickets/a/la-nature-art-and-musical-festival",
    text: "Art & Music Festival · 4 jours en pleine nature. Camping général inclus.",
    image: "images/la-nature.jpg",
  },

  {
    id: "mayr",
    title: "MAYR Radio Tour — Bruxelles",
    by: "MAYR Society",
    date: "2026-06-18",
    timeStart: "21:00",
    timeEnd: "02:00",
    venue: "C12",
    city: "Bruxelles",
    address: "Rue du Marché aux Herbes 116, 1000 Bruxelles",
    price: 9.99,
    styles: ["Rap", "UK Garage"],
    ticketUrl:
      "https://shotgun.live/fr/events/coelho-presente-le-mayr-radio-tour-bruxelles",
    lineup: ["Coelho", "DJ Sylaar"],
    text: "Coelho présente le MAYR Radio Tour · DJ set & live, format proche et vivant. Capacité limitée.",
    image: "images/mayr.png",
  },

  {
    id: "rebellious-wanted",
    title: "Rebellious × Barrio — WANTED",
    by: "RebelliousEvent",
    date: "2026-06-19",
    timeStart: "23:00",
    timeEnd: "06:00",
    venue: "Barrio BX",
    city: "Bruxelles",
    address: "Place de la Chapelle 6, 1000 Bruxelles",
    price: 20.0,
    styles: ["Acid Techno", "Hard Techno"],
    ticketUrl: "https://shotgun.live/fr/events/rebellious-x-barrio-brussels",
    lineup: [
      "Walker",
      "Beubeu x Matoz",
      "Slaycebee",
      "Le Bard",
      "Grayssoker",
      "Frikcion",
      "Farfacid",
    ],
    text: "Une line-up recherchée pour trouble à l'ordre public sonore. Ambiance brute, rebelle et sans compromis.",
    image: "images/rebellious-wanted.avif",
  },

  {
    id: "fox-rebellious",
    title: "The Fox's Hole × Rebellious",
    by: "RebelliousEvent",
    date: "2026-06-20",
    timeStart: "21:00",
    timeEnd: "05:00",
    venue: "Quai des Péniches",
    city: "Bruxelles",
    address: "Quai des Péniches, 1000 Bruxelles",
    price: 10.0,
    styles: ["Techno", "Électro"],
    ticketUrl: "https://shotgun.live/fr/events/the-fox-s-hole-rebellious",
    lineup: ["César", "Massilo", "Meven", "Minopolska", "RDKZ"],
    text: "Soirée Électro & Techno sur une péniche · Open Platine 21h-23h · cocktails sur mesure. Places limitées.",
    image: "images/fox-rebellious.avif",
  },

  {
    id: "c12",
    title: "C12 × Circle Park — Open Air + Afterparty",
    by: "C12 × Circle Park",
    date: "2026-06-20",
    endDate: "2026-06-21",
    timeStart: "14:00",
    timeEnd: null,
    venue: "Circle Park → C12",
    city: "Bruxelles",
    address: "116 rue Marché aux Herbes, 1000 Bruxelles",
    price: 10.0,
    styles: ["House", "Techno"],
    ticketUrl: "https://shop.c12space.com/6a96f65fe9804affbcc1a3c8bbcafbaa",
    lineup: [
      "Angel D'lite",
      "Fais Le Beau & Zouzibabe",
      "UNOS",
      "Byron Yeates",
      "VTT & Kathleen C",
      "Stanislawa",
    ],
    text: "15h non-stop : open air à Circle Park (14h-22h) puis afterparty au C12 jusqu'au lever du soleil.",
    image: "images/c12-openair.jpg",
  },

  {
    id: "nest-june",
    title: "N_JUNE",
    by: "Nest_bxl",
    date: "2026-06-28",
    timeStart: "10:00",
    timeEnd: "22:00",
    venue: "Lieu secret",
    city: "Bruxelles",
    address: "Lieu secret · ancienne usine",
    price: 20.55,
    styles: ["Techno", "House"],
    lineup: [],
    ticketUrl: "https://shotgun.live/fr/events/n-june",
    text: "After-party privé dans une ancienne usine, de 10h à 22h. « In edges we believe. »",
    image: "images/nest.avif",
  },

  {
    id: "district",
    title: "District Open Air",
    by: "District",
    date: "2026-07-04",
    timeStart: "16:00",
    timeEnd: "02:00",
    venue: "Brasserie Illegaal",
    city: "Vorst",
    address: "Rue Bollinckx 287, 1190 Vorst",
    price: 15.0,
    styles: ["Techno", "Open Air"],
    ticketUrl: "https://shop.weeztix.com/8669a77d-3e2f-4b6d-b6ea-891d3ec2e98c",
    lineup: ["PLASM", "BARTEL", "Tournesol", "STØRM", "JUCY", "ANT1", "LWSE"],
    image: "images/district.jpg",
  },

  {
    id: "gazmatek",
    title: "Gazmatek invite Alchimyst & Infrabass",
    by: "Gazmatek",
    date: "2026-07-04",
    timeStart: "22:00",
    timeEnd: "06:00",
    venue: "Buda BXL",
    city: "Bruxelles",
    address: "Chaussée de Buda 96, 1130 Bruxelles",
    price: 15.6,
    styles: ["Hardcore", "Industrial"],
    ticketUrl:
      "https://shotgun.live/fr/events/gazmatek-invite-alchimyst-infrabass",
    lineup: [
      "David Green",
      "Sevenum Six",
      "Looping",
      "T-Rence",
      "Terapeutek",
      "Olibrius",
      "Nocid",
      "Kemikal Crow",
      "Toff (vjing)",
      "Panoramix (vjing)",
    ],
    text: "Tekno industrielle & infrabass · mapping 3D · capacité limitée. Just tekno — no drugs, no violence, 18+.",
    image: "images/gazmatek.avif",
  },

  {
    id: "teletech",
    title: "Teletech Open Air Weekender",
    by: "Modul'air",
    date: "2026-07-04",
    endDate: "2026-07-05",
    timeStart: "13:00",
    timeEnd: null,
    venue: "Flanders Expo",
    city: "Gand",
    address: "Maaltekouter 1, 9051 Gent",
    price: 34.9,
    styles: ["Hard Techno", "Techno"],
    ticketUrl: "https://mdlr.be/teletech-tickets",
    lineup: [
      "2HOT2PLAY",
      "AZYR",
      "Emma Moon b2b Eva Vrijdag",
      "Miamor b2b Dr. G",
      "TDJ",
      "Ueberrest",
      "Jowi b2b Kirsty",
      "Lena De Roose",
      "Lolalita",
      "Natte Visstick",
      "Restricted",
      "William Luck",
    ],
    text: "4 & 5 juillet · 13:00–23:00 · strictly 18+ · paiement via app / carte RFID Modul'air.",
    image: "images/teletech.jpg",
  },

  {
    id: "boat",
    title: "C12 Boat Party",
    by: "C12 × Plaisirs d'Été",
    date: "2026-07-11",
    timeStart: "14:00",
    timeEnd: "22:30",
    venue: "Quai des Péniches",
    city: "Bruxelles",
    address: "Akenkaai 34, 1000 Bruxelles",
    price: 15.6,
    styles: ["House", "Disco"],
    ticketUrl: "https://quaidete-zomerkaai2026.ticketlive.be/schedule",
    lineup: [
      "Paulo Sea — 14:00-16:30",
      "Casper — 17:00-19:30",
      "Chris Ferreira — 20:00-22:30",
    ],
    text: "3 bateaux · 1 bateau = 1 ticket · capacité limitée, ne ratez pas le départ.",
    image: "images/boat-party.jpg",
  },

  {
    id: "doel",
    title: "Doel Festival 2026",
    by: "Doel Festival",
    date: "2026-07-25",
    timeStart: "12:00",
    timeEnd: "02:00",
    venue: "Village de Doel",
    city: "Doel",
    address: "Doel, Beveren",
    price: 75.0,
    styles: ["House", "Techno"],
    ticketUrl: "https://shop.paylogic.com/b76f0e83446d43afadbbe3ee635a3afc",
    lineup: [
      ".VRIL (live)",
      "BAMBII",
      "BLANKA",
      "Bitterbabe",
      "BSS",
      "Efdemin & nthng",
      "Hewan Aman",
      "Kevin Saunderson & Dantiez pres. E-Dancer",
      "Leafar Legov (live)",
      "Lola Haro",
      "Malibu",
      "RHR",
      "Rhadoo",
      "S.O.N.S",
      "Sarkawt Hamad",
      "Sedef Adasï",
    ],
    text: "Revitalising a Village through Music and Art · 5e édition · 14h durant.",
    image: "images/doel.jpg",
  },

  {
    id: "ronquieres",
    title: "Ronquières Festival 2026",
    by: "Ronquières Festival",
    date: "2026-08-07",
    endDate: "2026-08-09",
    timeStart: "14:00",
    timeEnd: null,
    venue: "Plaine de Ronquières",
    city: "Braine-le-Comte",
    address: "Route Baccara, 7090 Braine-le-Comte",
    price: null,
    styles: ["Pop", "Électro"],
    lineup: [],
    ticketUrl: null,
    text: "Festival sur 3 jours · 7, 8 & 9 août 2026.",
    image: "images/ronquieres.jpg",
  },

  {
    id: "colyn",
    title: "Colyn · Stavroz (live)",
    by: "Hangar",
    date: "2026-08-08",
    timeStart: "14:00",
    timeEnd: "00:00",
    venue: "Beach Open Air · KH Summercamp",
    city: "Knokke-Heist",
    address: "Evenementenstrand, Knokke-Heist",
    price: 48.5,
    styles: ["Melodic", "Open Air"],
    ticketUrl: "https://tickets.thehangar.be/",
    lineup: ["Colyn", "Stavroz (live)", "& support acts TBA"],
    text: "Beach Open Air · 14:00–00:00 · dernière entrée 19:00.",
    image: "images/colyn-stavroz.jpg",
  },

  {
    id: "xrds",
    title: "XRDS 2026",
    by: "XRDS × Fuse",
    date: "2026-08-14",
    endDate: "2026-08-15",
    timeStart: "13:00",
    timeEnd: null,
    venue: "Parc des Étangs · Vijverspark",
    city: "Anderlecht",
    address: "Av. Marius Renard 29A, 1070 Anderlecht",
    price: 70.0,
    styles: ["Techno", "House"],
    ticketUrl:
      "https://tickets.xrds.be/1e18d62e29c6499bbd7177d7e263e450/tickets",
    lineup: [
      "Ben Klock",
      "Ben UFO",
      "Goldie",
      "SHERELLE",
      "Mall Grab",
      "Roza Terenzi (live)",
      "Ryan Elliott",
      "Donato Dozzy",
      "Wata Igarashi & DJ Nobu",
      "Colin Benders (live)",
      "FJAAK (live)",
      "Dax J (live)",
      "Chlär",
      "Batu",
      "& many more",
    ],
    text: "Beneath the Brussels highways · curated by Fuse.",
    image: "images/xrds.jpg",
  },

  {
    id: "brejcha",
    title: "Boris Brejcha b2b Eric Prydz",
    by: "Hangar",
    date: "2026-08-15",
    timeStart: "15:00",
    timeEnd: "00:00",
    venue: "Royal Palace Open Air",
    city: "Bruxelles",
    address: "Place des Palais, 1000 Bruxelles",
    price: 57.5,
    styles: ["Minimal", "Techno"],
    ticketUrl: "https://tickets.thehangar.be/",
    lineup: ["Boris Brejcha b2b Eric Prydz", "& support acts TBA"],
    text: "World premiere b2b devant le Palais Royal · 15:00–00:00.",
    image: "images/brejcha-prydz.jpg",
  },

  {
    id: "energy",
    title: "Energy Festival 2026",
    by: "ENERGY Festival",
    date: "2026-09-04",
    endDate: "2026-09-06",
    timeStart: "17:00",
    timeEnd: null,
    venue: "Lotto Mons Expo",
    city: "Mons",
    address: "Avenue Thomas Edison 2, 7000 Mons",
    price: 56.99,
    styles: ["Hardstyle", "Hardcore"],
    ticketUrl: "https://shotgun.live/fr/festivals/energy-festival-3",
    lineup: [
      "DBSTF",
      "Radical Redemption",
      "Warface",
      "Ran-D",
      "Sound Rush",
      "Evil Activities",
      "Sickmode",
      "DJ Panic",
      "The Viper",
      "Act Of Rage",
      "D-Sturb",
      "N-Vitral",
      "Nosferatu",
      "Tha Playah",
      "& many more",
    ],
    text: "Le rendez-vous de la Hard Music · 90+ artistes, 6 scènes · Rawstyle, Uptempo, Hard Techno, Hardcore, Frenchcore…",
    image: "images/energy.png",
  },

  {
    id: "shrek",
    title: "Shrek Rave — Brussels",
    by: "Shrek Rave",
    date: "2026-10-03",
    timeStart: "21:00",
    timeEnd: "02:00",
    venue: "Claridge",
    city: "Bruxelles",
    address: "Claridge, Bruxelles",
    price: 25.0,
    styles: ["Rave"],
    lineup: [],
    ticketUrl: "https://likeit-loveit.com/eu/brands/shrek-rave",
    text: "Dress code : vert ou ton perso Shrek préféré. Shrek DJ set, visuals & singalongs.",
    image: "images/shrek-rave.jpg",
  },

  {
    id: "lobotomie",
    title: "Lobotomie",
    by: "",
    date: "2026-11-26",
    timeStart: "20:30",
    timeEnd: "05:00",
    venue: "Nashaz",
    city: "Bruxelles",
    address: "Rue Picard 3, 1000 Bruxelles",
    price: 0.0,
    styles: [],
    lineup: [
      "WC",
      "Droiture",
      "Sinusite",
      "DJ Shyddavis & Hotoliver",
      "DJ Froggy69",
      "KK slaughter",
    ],
    ticketUrl: "",
    text: "Une soirée faite par et pour les transpédégouines. Dress code : LOBOTOMIE",
    image: "images/lobotomie.jpeg",
  },

  {
    id: "tiesto",
    title: "Hangar invites Tiësto — Atomium Open Air",
    by: "Hangar",
    date: "2026-07-31",
    timeStart: "15:00",
    timeEnd: "00:00",
    venue: "Atomium",
    city: "Bruxelles",
    address: "Place de l'Atomium 1, 1020 Bruxelles",
    price: 67.5,
    styles: [],
    lineup: ["Tiësto"],
    ticketUrl:
      "https://l.facebook.com/l.php?u=http%3A%2F%2Ftickets.thehangar.be%2F%3Ffbclid%3DIwZXh0bgNhZW0CMTAAYnJpZBExYm1xTXVqZ2hGV0s3ZTRHZ3NydGMGYXBwX2lkEDIyMjAzOTE3ODgyMDA4OTIAAR4BKYz9qkGLxRQJqdiimgz6Yiq751NHDnjKYvD2xe3X4kxW7zTxk7bJSHLObA_aem_0SZ944IZzHnAate3-EkOAw&h=AUCmYAckmdl-KRYs2cFaT_4XHb3La2QRNmL_YJWTrmPOhYzQNEeZzZhzx_DGGscmqlwkHIVsJnm6VbMrCD0om7UwRQr7nfrkq-PxUixfoHTF8Wvu8M9rSsiLmYesXpEZdi_0N40esd7KohJ7WrFE_BpuDslBjFIjjC33wA&__tn__=q&c[0]=AUCPRlpIcIpsJ4OI5XUxmWLX4N5EvfKn3cPAGVTjL2LikxSVPLDJGNU-FLGSG0239jm0GQ1uTJt5FZ29SpiVC2EVTjk2MIrCcvEhFW_TouIF36uOf7iHBna2P6HeTsMq00EpnhHrH5bAkJ_dabiFSPyd0c-QuLfOXaM",
    text: "Tiësto returns for a first solo show in over a decade in Brussels, marking a rare and defining moment in his career.",
    image: "images/tiesto.jpg",
  },
  {
    id: "call-of-dirty-space-age",
    title: "C12 × Call of Dirty — Space Age",
    by: "C12 × Call of Dirty",
    date: "2026-10-03",
    timeStart: "23:00",
    timeEnd: "",
    venue: "C12",
    city: "Bruxelles",
    address: "116 rue Marché aux Herbes, 1000 Bruxelles",
    price: 11.0,
    styles: ["Techno"],
    ticketUrl: "https://shop.c12space.com/1aafe827ce624dfc9a7fa204c61dd863",
    lineup: ["CEM (Herrensauna)", "VTT", "Stella K", "soft:machina"],
    text: "Édition Space Age : couleurs vives, formes rondes et conversation pits en fourrure. Portes 23h, 18+, in = in / out = out. 11 € en early bird les 10 premiers jours.",
    image: "images/call-of-dirty.jpg",
  },

  {
    id: "soiree-casino-tr7",
    title: "Soirée Casino — 3e édition",
    by: "Table Ronde 7 de Charleroi",
    date: "2026-09-24",
    timeStart: "19:07",
    timeEnd: "",
    venue: "Avenue Marius Meurée",
    city: "Charleroi",
    address: "Avenue Marius Meurée 1, 6001 Charleroi",
    price: null,
    styles: [],
    ticketUrl: "https://www.facebook.com/events/1424577252862641/",
    lineup: [],
    text: "Repéré sur Facebook (marqué « Intéressé·e »). Soirée caritative de la Table Ronde 7 : tables de jeu, la bonne cause gagne à tous les coups.",
    image: "",
  },

  {
    id: "amelie-lens-kmska",
    title: "Amelie Lens in front of the KMSKA — Chaos in the City",
    by: "Chaosinthecity.events",
    date: "2026-09-05",
    timeStart: "14:00",
    timeEnd: "23:00",
    venue: "KMSKA · Leopold de Waelplaats",
    city: "Anvers",
    address: "Leopold de Waelstraat 17, 2000 Antwerpen",
    price: null,
    styles: ["Techno"],
    ticketUrl: "https://www.chaosinthecity.events/tickets",
    lineup: ["Amelie Lens", "Supporting acts TBA"],
    text: "Open air devant le Musée royal des Beaux-Arts d'Anvers. Repéré sur Facebook (Intéressé·e).",
    image: "images/amelie-lens-kmska.jpg",
  },

  {
    id: "voodoo-village-2026",
    title: "Voodoo Village 2026",
    by: "Voodoo Village",
    date: "2026-09-11",
    endDate: "2026-09-13",
    timeStart: "",
    timeEnd: "",
    venue: "Voodoo Village",
    city: "Grimbergen",
    address: "Warandestraat 100, 1851 Grimbergen",
    price: null,
    styles: ["Électro"],
    ticketUrl: "https://tickets.voodoovillage.be/",
    lineup: [],
    text: "Festival électronique en pleine nature, scènes déguisées. Repéré sur Facebook (Intéressé·e).",
    image: "images/voodoo-village.jpg",
  },

  {
    id: "boaf-2026",
    title: "Brussels Open Air Festival 2026",
    by: "La Fabriek × Brussels By Night × Easy Done × Vostock",
    date: "2026-09-12",
    timeStart: "14:00",
    timeEnd: "22:00",
    venue: "5 open airs (Congrès, Espagne, Vaux Hall, Jean Rey, Poelaert)",
    city: "Bruxelles",
    address: "Cinq lieux en plein air dans Bruxelles",
    price: null,
    styles: ["Open Air"],
    ticketUrl: "https://shop.paylogic.com/bad823ef8959466dba3c9066917cdf3f",
    lineup: ["21AM", "Bloody Louis", "Nashaz", "Fatma Soundsystem", "FEMMEBASS", "BIOME"],
    text: "3e édition : cinq open airs, un collectif par lieu, un festival pass pour circuler entre eux. Repéré sur Facebook (Intéressé·e).",
    image: "images/boaf.jpg",
  },

  {
    id: "biome-fabriek-boaf",
    title: "BIOME × La Fabriek — Brussels Open Air Festival",
    by: "La Fabriek × Brussels By Night",
    date: "2026-09-12",
    timeStart: "14:00",
    timeEnd: "22:00",
    venue: "La Fabriek (Studio CityGate)",
    city: "Anderlecht",
    address: "Rue de la Petite Île 1A, 1070 Anderlecht",
    price: null,
    styles: ["Open Air", "House"],
    ticketUrl: "https://shop.paylogic.com/13e9c7d3e75e4b82b21fb2c4197a04b8",
    lineup: [],
    text: "8 heures d'open air : c'est l'un des cinq lieux du Brussels Open Air Festival, pas un event concurrent. Repéré sur Facebook (Intéressé·e).",
    image: "",
  },

  {
    id: "24h-cycliste-wallonie",
    title: "24h Cycliste de Wallonie",
    by: "Circuit de Chimay × Cycling Force Chimay",
    date: "2026-09-12",
    endDate: "2026-09-13",
    timeStart: "15:00",
    timeEnd: "15:00",
    venue: "Circuit de Chimay",
    city: "Chimay",
    address: "Rue du Grand Prix des Frontières 1, 6460 Chimay",
    price: null,
    styles: [],
    ticketUrl: "https://www.facebook.com/events/1257462223120520/",
    lineup: [],
    text: "24 heures de vélo sur le circuit de Chimay. Repéré sur Facebook (Intéressé·e).",
    image: "",
  },

  {
    id: "fuse-ghost-gonno",
    title: "Fuse presents: The Ghost & Gonno",
    by: "Fuse",
    date: "2026-10-02",
    timeStart: "23:00",
    timeEnd: "07:00",
    venue: "Fuse",
    city: "Bruxelles",
    address: "Rue Blaes 208, 1000 Bruxelles",
    price: null,
    styles: ["Techno"],
    ticketUrl: "https://www.fuse.be/oct-02",
    lineup: ["The Ghost", "Gonno", "Penelope", "Nefeli"],
    text: "Room 01. Repéré sur Facebook (Intéressé·e).",
    image: "",
  },

  {
    id: "oktoberfest-cup",
    title: "Oktoberfest by C'UP",
    by: "C'UP — Charleroi Urban Project",
    date: "2026-10-03",
    timeStart: "18:00",
    timeEnd: "",
    venue: "Place de la Digue",
    city: "Charleroi",
    address: "Place de la Digue 31, 6000 Charleroi",
    price: null,
    styles: [],
    ticketUrl: "https://www.facebook.com/events/1606499450977611/",
    lineup: [],
    text: "2e édition de l'Oktoberfest carolo. Repéré sur Facebook (Intéressé·e).",
    image: "",
  },

  {
    id: "marche-climat-2026",
    title: "Marche Climat 2026",
    by: "Coalition Climat & 4 autres",
    date: "2026-10-11",
    timeStart: "14:00",
    timeEnd: "",
    venue: "Gare du Nord",
    city: "Bruxelles",
    address: "Gare du Nord, 1000 Bruxelles",
    price: null,
    styles: [],
    ticketUrl: "https://www.marcheclimat.be/",
    lineup: [],
    text: "Marche pour le climat, départ Gare du Nord. Repéré sur Facebook (Intéressé·e).",
    image: "",
  },

  {
    id: "rave-rebels-xxl",
    title: "Kompass presents Rave Rebels XXL Weekender",
    by: "Rave Rebels × Garage Klub × Kompass",
    date: "2026-11-06",
    endDate: "2026-11-08",
    timeStart: "19:00",
    timeEnd: "07:00",
    venue: "ING Arena",
    city: "Bruxelles",
    address: "Parc des Expositions, 1020 Bruxelles",
    price: null,
    styles: ["Techno", "Rave"],
    ticketUrl: "https://shop.raverebels.com/52d1436202b643718d15f2307af4623a",
    lineup: [],
    text: "La plus grosse rave indoor de Belgique, vendredi 6 et samedi 7 novembre. Repéré sur Facebook (Intéressé·e).",
    image: "images/rave-rebels.webp",
  },

  {
    id: "ecosocialisme-2026",
    title: "[REPORTÉ] Écosocialisme 2026 — Une boussole dans la tempête",
    by: "Gauche anticapitaliste × SAP × Formation Léon Lesoil",
    date: "2026-09-04",
    endDate: "2026-09-06",
    timeStart: "16:00",
    timeEnd: "17:00",
    venue: "Maison Notre-Dame du Chant d'Oiseau",
    city: "Woluwe-Saint-Pierre",
    address: "Woluwe-Saint-Pierre, Bruxelles",
    price: null,
    styles: [],
    ticketUrl: "https://www.facebook.com/events/1501888587610778/",
    lineup: [],
    text: "⚠ Reporté à une date ultérieure par les organisateurs. Repéré sur Facebook (Intéressé·e).",
    image: "",
  },
];


export { DATA };
